# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin_api_payment_method:
    resource: |
        identifier: code
        alias: sylius.payment_method
        section: admin_api
        grid: sylius_admin_api_payment_method
        form: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodType
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api

sylius_admin_api_payment_method_create:
    path: /payment-methods/{factory}
    methods: [POST]
    defaults:
        _controller: sylius.controller.payment_method:createAction
        _sylius:
            serialization_groups: [ Default, Detailed ]
            serialization_version: $version
            section: admin_api
            form: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodType
            factory:
                method: createWithGateway
                arguments:
                    gatewayFactory: $factory
            vars:
                route:
                    parameters:
                        factory: $factory
